FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git

COPY requirements.txt .
COPY tests/requirements-test.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-test.txt

RUN pip install pytest

COPY . .

ENV PYTHONPATH=/app

CMD [ "pytest", "--maxfail=1", "--disable-warnings", "tests/" ]
