FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache \
    gcc \
    g++ \
    make \
    libffi-dev \
    openssl-dev \
    musl-dev \
    jpeg-dev \
    zlib-dev \
    bash \
    git

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN git submodule update --init --recursive

ENV PYTHONPATH=/app/kindwise-api-client:$PYTHONPATH

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
