# Dockerfile-test
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Install git and other dependencies
RUN apt-get update && apt-get install -y git

# Copy requirements file to install dependencies
COPY requirements.txt .
COPY tests/requirements-test.txt .

# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-test.txt

# Install test-related dependencies
RUN pip install pytest

# Copy the rest of the application
COPY . .

# Set PYTHONPATH to make src directory discoverable
ENV PYTHONPATH=/app

# Run the tests using pytest
CMD [ "pytest", "--maxfail=1", "--disable-warnings", "tests/" ]
