FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache git gcc musl-dev libjpeg-turbo-dev zlib-dev

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN git submodule update --init --recursive

ENV PYTHONPATH="/app/kindwise-api-client:$PYTHONPATH"

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
